# Generated by Django 5.0.1 on 2024-01-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_superhero_delete_post_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='SuperHero',
        ),
    ]
