# Generated by Django 5.0.1 on 2024-01-18 10:37

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9 ]+$')])),
                ('destination', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9 ]+$')])),
                ('date_time', models.DateTimeField(validators=[app.models.date_time_is_in_the_future])),
                ('price_in_cents', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
            ],
        ),
    ]
