# Generated by Django 5.0.1 on 2024-01-11 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[A-Za-z0-9 ]*')])),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[A-Za-z0-9 ]*')])),
                ('genre', models.CharField(choices=[('ROCK', 'Rock'), ('RAP', 'Rap'), ('TRAP', 'Trap'), ('COUNTRY', 'Country'), ('PUNK', 'Punk'), ('HOUSE', 'House'), ('DANCE', 'Dance')], max_length=10)),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3600)])),
            ],
        ),
    ]
