# Generated by Django 5.0.1 on 2024-01-11 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_delete_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\w]*$')])),
                ('category', models.CharField(choices=[('ELE', 'Electronics'), ('FSH', 'Fashion'), ('HOM', 'Home'), ('BTY', 'Beauty'), ('SPO', 'Sports'), ('BKS', 'Books')], max_length=15)),
                ('price_in_cents', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)])),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
            ],
        ),
    ]
