# Generated by Django 5.0.1 on 2024-01-11 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[A-Za-z0-9 ]*')])),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[A-Za-z0-9 ]*')])),
                ('genre', models.CharField(choices=[('DRA', 'Drama'), ('COM', 'Comedy'), ('ACT', 'Action'), ('THR', 'Thriller'), ('HOR', 'Horror'), ('SCI', 'Sci-fi'), ('ANI', 'Animation')], max_length=10)),
                ('duration_in_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
            ],
        ),
    ]
