# Generated by Django 5.0.1 on 2024-01-12 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
