# Generated by Django 5.0.1 on 2024-01-16 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z]$')])),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9]*$')])),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9 ]*$')])),
                ('category', models.CharField(choices=[('APPETIZER', 'Appetizer'), ('FIRST COURSE', 'First Course'), ('SECOND COURSE', 'Second Course'), ('SIDE DISH', 'Side Dish'), ('DESSERT', 'Dessert'), ('BEVERAGE', 'Beverage')], max_length=20)),
                ('ingredients', models.ManyToManyField(to='app.ingredient')),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
